### 넘파이의 ndarray의 데이터 세트 선택하기 - 인덱싱(Indexing)
*넘파이에서 ndarray내의 일부 데이터 셋이나 특정 데이터만을 선택 할 수 있도록 하는 인덱싱에 대한 알아보자
#### 1.특정한 데이터만 추출
#### 2.슬라이싱(Slicing)
#### 3.팬시 인덱싱(Fancy Indexing)
#### 4.불리언 인덱싱(Boolean Indexing)

In [2]:
import numpy as np

In [8]:
# 1~9까지 1차원 ndarray생성 -np.arange
array1 = np.arange(1, 10)
value = array1[len(array1)-1]
print('value: ', value)
print(type(value))

value:  9
<class 'numpy.int32'>


In [10]:
# array1을 2차원으로 변형
array1d = array1.copy()
array2d = array1d.reshape(3,3)
print(array2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [15]:
print('(row = 0, col=0) index 가리키는 값: ', array2d[0,0])  # [0][0]
print('(row = 0, col=1) index 가리키는 값: ', array2d[0,1])  #[0][1]
print('(row = 1, col=0) index 가리키는 값: ', array2d[1,0])

(row = 0, col=0) index 가리키는 값:  1
(row = 0, col=1) index 가리키는 값:  2
(row = 1, col=0) index 가리키는 값:  4


## 2.슬라이싱(Slicing) - 2차원

In [19]:
print(array2d)

print('array2d(0:3, 0:2): \n', array2d[0:3, 0:2])
print('array2d(0:2, 0:2): \n', array2d[0:2, 0:2])
print('array2d(1:, 0:3): \n', array2d[1:, :])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d(0:3, 0:2): 
 [[1 2]
 [4 5]
 [7 8]]
array2d(0:2, 0:2): 
 [[1 2]
 [4 5]]
array2d(1:, 0:3): 
 [[4 5 6]
 [7 8 9]]


In [20]:
## question 1
print('array2d(:2, 0): \n', array2d[:2, 0])
print('array2d(:2, 0:1): \n', array2d[:2, 0:1])

array2d(:2, 0): 
 [1 4]
array2d(:2, 0:1): 
 [[1]
 [4]]


### 3. 팬시 인덱싱(Fancy Indexing)

In [22]:
print(array2d)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
array2d[[0,1],2]  # 2 => 3,6,9   /  
array2d[[0,1],2:]

array([[3],
       [6]])

In [26]:
array2d[[0,2],2:]

array([[3],
       [9]])

In [27]:
array2d[[0,2],[1,1]]

array([2, 8])